L11/Calc/config/routes.rb
Rails.application.routes.draw do
  root to: 'calculations#index'
  resources :calculations, only: [:index, :new, :create, :destroy]
  get 'calculations/result'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

L11/Calc/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

L11/Calc/app/models/calculation.rb
class Calculation < ApplicationRecord
  before_create :calculate
  ############ Валидация #####################
  validates :source_numbers, presence: true, uniqueness: true 
  ############################################
  def calculate
    #Математика из 8-ой лабы

    source_arr = source_numbers.split(/\D/).reject { |x| x == '' }
    n = source_arr.length
    source_arr = source_arr.slice!(0..n).map(&:to_i)
    final_arr = []
    source_arr.each_index do |index|
      final_arr.push([])
      source_arr[index..n].each do |x|
        break unless perfect?(x)
  
        final_arr[index].push(x)
      end
    end
    final_arr.reverse[0...final_arr.length - 1].each_with_index do |elem, index|
    if elem.reverse == final_arr.reverse[index + 1].reverse[0...elem.length]
      final_arr[final_arr.length - index - 1] = []
      end
    end
    final_arr.reject! { |x| x == [] }
    @arr = final_arr
    @max_arr = final_arr.max_by(&:length)
    @quantity = final_arr.length
    unless @arr.any?
      @arr = [[0,0],[0,0],[0,0]]
    end
   self.results = @arr
  end
  #Модифицировать модель таким образом, чтобы добавление записей с одинаковыми параметрами было невозможно.
  #https://guides.rubyonrails.org/active_record_validations.html
  end

  private
  def divisor_by_factorization(number)
    return [1] if number == 1
    primes, powers = Prime.prime_division(number).transpose
    exponents = powers.map { |i| (0..i).to_a }
    divisors = exponents.shift.product(*exponents).map do |powers|
      primes.zip(powers).map{ |prime, power| prime**power}.inject(:*)
    end
    divisors.sort
  end

  def perfect?(number)
    return false if divisor_by_factorization(number).length == 1
    divisor_by_factorization(number)[0...-1].inject(0) do |sum, x|
      x + sum
      end == number
    end

L11/Calc/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

L11/Calc/app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def new
    @calculation = Calculation.new()
  end

  def index
    @calculations = Calculation.all
  end

  def create
    if Calculation.new(params[:calculation].permit(:source_numbers)).valid?
      @calculation = Calculation.new(params[:calculation].permit(:source_numbers))
      if @calculation.save
      redirect_to calculations_path
      else
      render 'new'
      end
    else
      redirect_to calculations_path
    end
    
  end

  def destroy
    @calculation = Calculation.find(params[:id])
    @calculation.destroy
    redirect_to calculations_path
  end
  def result
    @res = Calculation.all
    render xml: @res
  end
end

L11/Calc/app/helpers/application_helper.rb
module ApplicationHelper
end

L11/Calc/app/helpers/calculations_helper.rb
module CalculationsHelper
end

L11/Calc/app/views/calculations/index.html.erb
<% @calculations.each do |calculation|%>
<div><%= calculation.source_numbers %></div>
<%# arr ||= JSON.parse(calculation.results) %>
<table border="2">
    <tr>
        <th>Количество</th>
        <th>Все отрезки</th>
        <th>Самый длинный</th>
    </tr>

    <tr>
        <td rowspan="<%= calculation.results.length %>"><%= calculation.results.length %></td>
        <td><%= calculation.results[0] %></td>
        <td rowspan="<%= calculation.results.length %>"><%= calculation.results.max %></td>
    </tr>

    <% calculation.results[1..calculation.results.length].each do |x| %>
    <tr>
        <td><%= x %></td>
        <% end %>
    </tr>
 
</table>
<div><%= link_to 'Удалить', calculation, method: :delete %></div>
<% end %>
<%= link_to 'Добавить', new_calculation_path %>
<%= link_to 'XML', calculations_result_path, :method => "get" %>

L11/Calc/app/views/calculations/new.html.erb
<%= form_for @calculation do |f| %>
<%= f.label :source_numbers %>
<%= f.text_field :source_numbers %>
<% end %>

L11/Calc/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <br>
    <br>
    <br>

    <%= yield %>
  </body>
</html>